### ISSUE TITLE
unable to open file: name = 'full_yolo_backend.h5'

### ISSUE THREAD

**Issue by coderrsid** [jhasuman/potholes-detection#4]
<img width="1263" alt="Screenshot 2019-03-26 at 1 37 36 AM" src="https://user-images.githubusercontent.com/35633575/54950662-c2352780-4f67-11e9-9e26-d064cfcf1687.png">

Can anyone help please?

**Comment by ghost** [comment]
@coderrsid did you trained that model with your dataset successfully?
